Сделал пакет react-responsive
al-revenko/react-responsive pull request #1
Opened 2024-07-08 11:09 UTC by al-revenko

2024-07-08 12:45 UTC, aidagalimova commented on react-responsive/src/useMediaQuery/index.ts
> +  }, [matchValue, query]);
не уверена, но не лучше сделать пустой массив там где есть addEventListener?

2024-07-08 12:50 UTC, aidagalimova commented on react-responsive/src/MediaQuery/index.tsx
> +    createQuery('max-height', maxHeight),
почему для каждного отдельный вызов функции, а не в цикле по пропсам?

2024-07-08 12:55 UTC, aidagalimova commented on react-responsive/src/MediaQuery/index.tsx
> +  minWidth: number | `${number}px`;
можно создать отдельные типы для `number | ${number}dppx`  и  `number | ${number}px` чтобы не дублировать

2024-07-08 13:14 UTC, aidagalimova commented on react-responsive/src/MediaQuery/index.tsx
> +  children: ReactNode | ((match: boolean) => ReactElement);
не лучше использовать `((match: boolean) => ReactNode`?

2024-07-08 15:39 UTC, aidagalimova commented on react-responsive/src/useMediaQuery/index.ts
> +  const [matchValue, setMatchValue] = useState(false);
начальное состояние можно из matches взять

2024-07-09 04:54 UTC, al-revenko commented on react-responsive/src/MediaQuery/index.tsx
> +  minWidth: number | `${number}px`;
да, лучше сделать так

2024-07-09 05:01 UTC, al-revenko commented on react-responsive/src/MediaQuery/index.tsx
> +  children: ReactNode | ((match: boolean) => ReactElement);
да, так лучше

2024-07-09 05:32 UTC, al-revenko commented on react-responsive/src/useMediaQuery/index.ts
> +  const [matchValue, setMatchValue] = useState(false);
Тогда придётся сделать так 
```js
export const useMediaQuery = ({ query }: HookArgs): boolean => {
  const media = window.matchMedia(query);
  const [matchValue, setMatchValue] = useState(media.matches);

  useEffect(() => {
    const handler: HandlerType = ({ matches }) => setMatchValue(matches);

    media.addEventListener('change', handler);

    return () => media.removeEventListener('change', handler);
  }, [matchValue, media]);

  return matchValue;
};
```

Я так изначально и сделал, но столкнулся с проблемой что при такой реализации и при таких "пограничных" query:
```js
  const isDesktopOrLaptop = useMediaQuery({ query: '(min-width: 1224px)' });
  const isTabletOrMobile = useMediaQuery({ query: '(max-width: 1224px)' }); 
```
```js
    <div style={{ fontSize: '30px' }}>
      <h1>Device Test! (useMediaQuery)</h1>
      {isDesktopOrLaptop && <p>You are a desktop or laptop</p>}
      {isTabletOrMobile && <p>You are a tablet or mobile phone</p>}}
    </div>
```

появляются странности с рендером:

![2024-07-09_12-22-58](https://github.com/al-revenko/react-responsive/assets/73707133/9e643b10-2315-4d50-9431-81b057250c35)
![1](https://github.com/al-revenko/react-responsive/assets/73707133/42021551-8dbd-444c-82ce-1c72db1e7d27)

2024-07-09 06:02 UTC, al-revenko commented on react-responsive/src/MediaQuery/index.tsx
> +    createQuery('max-height', maxHeight),
Потому что это намного сложнее. Пришлось бы делать дополнительную логику, а это: долго, сложно, код будет сложнее читать и самое главное не понятно зачем это делать.

1. Пропсы вещь статическая и её свойства не меняются по ходу рантайма, они нам все известны. Цикл имело бы смысл делать если бы итерируемый объект имел неизвестные нам свойства или если бы этих свойств было очень много.

2. Мне пришлось бы сопоставлять пропсы и query параметры (например пропс minWidth это query параметр min-width)

3. Пришлось бы сопоставлять определённые пропсы и их единицы измерения (например у minResolution это dppx, а у orientation вообще нет этих единиц)

4. Пришлось бы фильтровать не media пропсы (в данном случае исключить children из цикла)

5. Я не уверен, но наверное пришлось бы делать 2‑й цикл. 1‑й для цикличного вызова createQuery и 2й, для того чтобы сложить результаты этих вызовов в одну query строку

Моя реализация немного глупая, но зато крайне простая)

2024-07-09 09:02 UTC, aidagalimova commented on react-responsive/src/useMediaQuery/index.ts
> +  const [matchValue, setMatchValue] = useState(false);
а если так? `const [matchValue, setMatchValue] = useState(window.matchMedia(query).matches);`

2024-07-09 09:52 UTC, aidagalimova commented on react-responsive/src/MediaQuery/index.tsx
> +    createQuery('max-height', maxHeight),
Просто выглядит немного захардкожено, но окэй) 
4. при деструктуризации props можно удобно отфильтровать` {children, ...queries}`
5. в этой реализации в принципе тоже два цикла, вызовы createQuery и reduce

2024-07-09 09:53 UTC, al-revenko commented on react-responsive/src/useMediaQuery/index.ts
> +  const [matchValue, setMatchValue] = useState(false);
Сейчас matchMedia(query) вызывается 1 раз, если сделаю так, то будет вызываться 2 раза, снаружи и внутри useEffect:

```js
  const [matchValue, setMatchValue] = useState(window.matchMedia(query).matches);

  useEffect(() => {
    const media = window.matchMedia(query);

    if (media.matches !== matchValue) {
      setMatchValue(media.matches);
    }
```

И как бы всё)

Логика выполнения не изменится, но на 1 лишний вызов функции будет больше. Это имело бы смысл если бы я вынес media наверх, но как я и писал выше из-за этого рендер ведёт себя очень странно 

```js
  const media = window.matchMedia(query);
  const [matchValue, setMatchValue] = useState(media.matches);

  useEffect(() => {
    const handler: HandlerType = ({ matches }) => setMatchValue(matches);
```

2024-07-09 10:00 UTC, aidagalimova approved these changes

2024-07-09 12:18 UTC, Kalabass requested changes

2024-07-09 12:18 UTC, Kalabass commented on react-responsive/src/useMediaQuery/index.ts
> +}
в хук тоже должна быть возможность передачи нескольких атрибутов 
![image](https://github.com/al-revenko/react-responsive/assets/128186514/26da09cd-c318-4549-ab87-b5efdc1cbe40)

2024-07-09 13:16 UTC, Kalabass approved these changes

2024-07-11 09:18 UTC, G00syara approved these changes

2024-07-14 09:45 UTC, sspopkov approved these changes

2024-07-14 09:45 UTC, merged